icons = "material-nf"

[theme]
name = "solarized-dark"
[theme.overrides]
separator = ""

[[block]]
block = "bluetooth"
mac = "00:08:E0:61:ED:29"
format = "Speaker"

[[block]]
block = "bluetooth"
mac = "38:18:4C:D3:F5:A0"
format = "Headphone"

[[block]]
block = "music"
max_width = 50
dynamic_width = true
buttons = ["play"]
