icons = "material-nf"

[theme]
name = "solarized-dark"
[theme.overrides]
separator = ""

[[block]]
block = "sound"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "memory"
interval = 5
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "disk_space"
path = "/"
format = "{icon} {available} {percentage}"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp3s0"
format = "{ssid}"
format_alt = "{ip} {ipv6}"
interval = 5

[[block]]
block = "battery"
interval = 15
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m.%Y %R"
